# Numpy y Pandas
## Para que sirven?
- Numpy es una librería que permite hacer un cálculo numérico 
- Manejar arrays
## Pandas 
- Manipulación y análisis de datos

## numpy
### Array
- La estructura central es de NumPy
- Representa datos de manera estructurada
- Indexado
- Acceso a uno o muchos elemntos

#### Ejemplo de una array en numpy

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
lista = [i for i in range(1, 10)]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]+arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0, 2]

3

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slicing
Slicing sirve para extraer más de un elemento, podemos indicar la posición inicial y la posición final usando `:` como separador. Eso lo podemos ver en los siguientes ejemplos

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
listai = np.arange(9, 0, -1)
listai[::-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-3:]

array([7, 8, 9])

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>