In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.arange(1, 5, dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.arange(0,5)
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.arange(0,5)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [ ]:
import tensorflow as tf

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>