# Dimensiones de datos en numpy

<img src="/work/ai/assets/first.png">

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
scalar
scalar.ndim

0

In [ ]:
vector = np.arange(1,4)
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
matriz = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(matriz)
matriz.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [ ]:
tensor = np.array([[[1,2,3], [4,5,6], [7,8,9], [0, 2,45]], [[1,2,3], [4,5,6], [7,8,9], [0, 2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
print(expand.ndim)
print(expand.shape)

[[1 2 3]]
2
(1, 3)


## Método Squeeze
La función squeeze se usa para remover  

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(f"vector: {vector_2} \ndimensiones: {vector_2.ndim}")

[[[[[[[[[[1 2 3]]]]]]]]]] 10
vector: [1 2 3] 
dimensiones: 1


In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


# Reto
1. Definir un tensor con al menos 5 dimensiones
2. Sumarle una dimensión en cualquiera de los ejes
3. Borrar las dimensiones que no se usan

In [ ]:
nuevo_tensor = np.array([np.arange(1,4), np.arange(4, 7), np.arange(7, 10)], ndmin=5)
print(nuevo_tensor)
print('------------')
print(nuevo_tensor.ndim)
print('------------')
print(nuevo_tensor.shape)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
------------
5
------------
(1, 1, 1, 3, 3)


In [ ]:
nuevo_tensor = np.squeeze(nuevo_tensor)
print(nuevo_tensor)
print(nuevo_tensor.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>