In [ ]:
import numpy as np

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0, 10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.6821680332713103

In [ ]:
np.random.rand(4)

array([0.02606301, 0.60321819, 0.33484119, 0.30617712])

In [ ]:
np.random.rand(4,4)

array([[0.597051  , 0.76576355, 0.31130039, 0.65575868],
       [0.27875299, 0.59229005, 0.76355672, 0.705411  ],
       [0.77193956, 0.66090431, 0.98826492, 0.52084651],
       [0.46482867, 0.178648  , 0.11411392, 0.39846836]])

In [ ]:
np.random.randint(1, 15)

7

In [ ]:
np.random.randint(1, 100, (10,10))

array([[ 6, 51, 49, 33, 97, 98, 52, 92, 17, 10],
       [18, 75, 66, 88, 51, 77, 91, 39, 65, 61],
       [97, 97, 30, 34, 66, 55, 79, 67, 11, 95],
       [97, 40, 60, 29, 70, 57, 68, 95, 94, 54],
       [ 7, 48, 50, 61, 69, 90,  1,  9, 10, 44],
       [99,  6, 53, 45, 83, 57, 85, 83, 39, 35],
       [95, 42,  9,  4, 68,  8,  3, 81, 38, 69],
       [41, 91,  7, 59, 77, 91, 19, 37, 70, 67],
       [11, 35, 51, 76, 95, 37, 92, 66, 41, 33],
       [77, 11, 19, 39, 62,  9, 31, 12, 36, 65]])

In [ ]:
np.random.random_integers(1, 100, (10,10))

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  """Entry point for launching an IPython kernel.


array([[ 76,  87,  90,  17,  27,  26,  71,  93,  86,  59],
       [ 97,  69,  87,  52,  57,   9,  79,  56,  15,  73],
       [ 81,  24,   6,  92, 100,  67,  32,  31,  46,  44],
       [ 47,  29,  17,  23,   6,  59,   3,  99,  72,   4],
       [ 92,  56,  42,  74,  52,  20,  94,  22,  12,  11],
       [ 65,  45,  44,  53,  49,  71, 100,  69,   4,   2],
       [ 80,  15,  78,  44,   3,  69,  95,  51,  34,  27],
       [ 52,  34,  48,  99,  69,   8,  81,  84,  61,  24],
       [  6,  91,  98,  99,  45,  86,  11,  18,  58,   6],
       [ 42,  21,  84,  93,  33,  29,  62,  17,  18,  90]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>