In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 10, (3,2))

In [ ]:
arr.shape

(3, 2)

In [ ]:
 arr

array([[6, 8],
       [7, 9],
       [5, 7]])

In [ ]:
arr.reshape(1,6)

array([[6, 8, 7, 9, 5, 7]])

In [ ]:
arr.reshape(2,3)

array([[6, 8, 7],
       [9, 5, 7]])

In [ ]:
arr.reshape(3, 2)

array([[6, 8],
       [7, 9],
       [5, 7]])

In [ ]:
arr

array([[6, 8],
       [7, 9],
       [5, 7]])

In [ ]:
np.reshape(arr, (1,6))

array([[6, 8, 7, 9, 5, 7]])

In [ ]:
arr

array([[6, 8],
       [7, 9],
       [5, 7]])

In [ ]:
np.reshape(arr, (2,3), 'C')

array([[6, 8, 7],
       [9, 5, 7]])

In [ ]:
np.reshape(arr, (2,3), 'F')

array([[6, 5, 9],
       [7, 8, 7]])

In [ ]:
np.reshape(arr, (2,3), 'A')

array([[6, 8, 7],
       [9, 5, 7]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>