In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 20, 10)

In [ ]:
arr

array([17,  5,  1, 15,  7,  6,  6, 17, 13,  9])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[17,  5,  1, 15,  7],
       [ 6,  6, 17, 13,  9]])

In [ ]:
matriz.max()

17

In [ ]:
matriz

array([[17,  5,  1, 15,  7],
       [ 6,  6, 17, 13,  9]])

In [ ]:
matriz.max(1)

array([17, 17])

In [ ]:
arr.argmax()

0

In [ ]:
matriz.argmax()

0

In [ ]:
matriz.argmax(0)

array([0, 1, 1, 0, 1])

In [ ]:
np.sort(arr)

array([ 1,  5,  6,  6,  7,  9, 13, 15, 17, 17])

In [ ]:
np.sort(matriz)

array([[ 1,  5,  6,  6,  7],
       [ 9, 13, 15, 17, 17]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>