In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_arr = arr[0:6]

In [ ]:
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_arr[:] = 0
trozo_arr 

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_with_copy = np.arange(0, 10)
arr_with_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_copy_trozo = np.copy(arr_with_copy)

In [ ]:
arr_copy_trozo[:] = 0
arr_copy_trozo 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr_with_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>