In [ ]:
import numpy as np

In [ ]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr>5] = 99

In [ ]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [ ]:
np.linspace(start = 0, stop = 100, num = 5, )

array([  0.,  25.,  50.,  75., 100.])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>