In [ ]:
import numpy as np

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista*2

[1, 2, 1, 2]

In [ ]:
arr = np.arange(10)
arr2 = arr.copy()

## Operaciones 

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1/arr

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [ ]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>