# Constantes

In [ ]:
import tensorflow as tf 
import numpy as np
tf.__version__

'2.9.0'

## Definir una constante

In [ ]:
# Definimos una constante en tensorflow
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
# Obtenemos el tamña de un tensor
tensor_20.shape

TensorShape([2, 2])

## Consultar los valores de una constante

In [ ]:
# Obtenemos los valores de nuestra constante desde el array de numpy
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
# Podemos convertir un array de numpy directamente a un tensor flow
new_tensor = np.array([[23, 4], [32, 51]])
tensor_from_numpy = tf.constant(new_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# Variables

## Definir una variable

In [ ]:
tf2_variable = tf.Variable([np.arange(1., 4.), np.arange(4., 7.)])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

## Consultar los valores de una variable

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]])

## Cambiar un valor específico de una varibale

In [ ]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float64, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]])>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]])>

## Opreciones con `tensores`

In [ ]:
tensor = tf.constant([[1,2], [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Sumar un escalar a un tensor

In [ ]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

## Multiplicar un escalar por un tensor

In [ ]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

## Utilizar funciones de Numpy sobre tensores de TensorFlow

In [ ]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

## Producto escalar entre dos tensores

In [ ]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

## Strings en tensorflow

In [ ]:
tf_string = tf.constant('TensorFlow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

## Operaciones simples con `strings`

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

# Almacenar arrays de strings

In [ ]:
tf_strings_array = tf.constant(["TensorFlow", "Deeplearning", "AI"])

In [ ]:
# Iterar sobre un array de string en TF
for string in tf_strings_array:
    print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deeplearning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=837cf1af-c506-4091-b16c-c4a4c0575614' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>