# Conceptos fundamentales de tensorflow

Lo que se cubrirá será:

- Introducción a tensores
- obtener información de los tensores
- Manipular tensores
- Tensores & NumPy
- Usar @tf.function (una forma de acelerar las funciones regulares de python)
- Usar GPUs con tensorflow (o TPUs)

# Introducción a tensorflow

## Crear tensores con la constante `tf.constant()`

In [ ]:
# Importar TensorFlow
import pandas as pd
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.9.1


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Checar el número de dimensiones de un tensor (`ndim` representa el número de dimensiones)

In [ ]:
scalar.ndim

0

### Crear un vector

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

### Checar la dimensión de nuestro vector

In [ ]:
vector.ndim

1

### Crear una matriz (Que tenga más de una dimensión)
<a id='another_cell'></a>

In [ ]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### Checar el número de dimensiones

In [ ]:
matrix.ndim

2

### Crear una nueva matriz

Especificar el tipo de dato con el parámetro `dtype`

In [ ]:
another_matrix = tf.constant(
                            [[10., 7.],
                            [3., 2.], 
                            [8., 9.]],
                            dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

### Crear un tensor

In [ ]:
tensor = tf.constant([[
    np.arange(1,4),
    np.arange(4,7)],
    [np.arange(7,10),
    np.arange(10, 13)],
    [np.arange(13, 16),
    np.arange(16, 19)]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Resumen de esta sesión:
- Scalar: Un solo número
- Vector: Un número con `dirección` (e.g. la velocidad del viento en una dirección)
- Matriz: Un Array de numeros de 2 dimensiones
- Tensor: un Array de numeros de n-dimensiones

<img src="/work/ai/assets/first.png">

## Crear tensores con `tf.variable`

Creamos el mismo tensor con `tf.Variable()`

In [ ]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

Ahora intentamos cambiar uno de los elementos del tensor `changeable_tensor`

In [ ]:
try:
    changeable_tensor[0] = 7
    changeable_tensor
except TypeError:
    print('TypeError: ResourceVariable object does not support item assignment')
    

TypeError: ResourceVariable object does not support item assignment


Ahora lo intentamos con el método `.assign()`

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Ahora intentamos lo mismo pero con la variable `unchangeable_tensor`

In [ ]:
try:
    unchangeable_tensor[0].assign(7)
    unchangeable_tensor 
except AttributeError:
    print('AttributeError: tensorflow.python.framework.ops.EagerTensor object has no attribute assign')

AttributeError: tensorflow.python.framework.ops.EagerTensor object has no attribute assign


🔑 **Nota:** En la práctica en muy raros casos vamos a necesitar decidir cual de los tipos de tensores usar, `tf.constant` y `tf.Variable` para crear tensores ya que tensorflow lo hace por nosotros.
Pero si en algún caso no sabes que poner usa `tf.constant` y cambialo después si es necesario.

## Crear tensores `random`

Los tensores random son tensores de un tamaño arbitrario que contiene numeros random

In [ ]:
# Crear dos tensores de forma random (pero iguales)
random_1 = tf.random.Generator.from_seed(42) # establecer semilla de reproducibilidad
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Son iguales?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Barajar el orden de elementos de un tensor
Barajar un tenso)

In [ ]:
# Shuffle a tensor o Barajear un tensor 
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Ejercicio**: Leer la documentación de `tensorflow` para generar [`random seed`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed):

Practicar escribiendo 5 tensores random

Parece que si queremos que nuestros tensores barajados estén en el mismo orden, tenemos que usar la semilla aleatoria de nivel global, así como la semilla aleatoria de nivel de operación:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."


In [ ]:
tf.random.set_seed(42) # Global level random
tf.random.shuffle(not_shuffled, seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Otras formas de crear tensores

In [ ]:
# Creat tensores con puros unos
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Crear tensores con puros ceros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Convertir arrays de numpy en tensores

La principal diferencia entre arrays de numpy y los tensores de tensorflow es que los tensores puden correr en una gpu mucho más rápido para la computación numérica

In [ ]:
# Tambien podemos convertir arrays de numpy a tensores
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Crear un array de numpy entre 1 y 25
numpy_A

# X = tf.constant(some_matrix) # Se una la mayuscula para matrizes o tensores
# y = tf.constant(vector) # non-capital se usa para vectores

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A, )
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A, )
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

2

### Obtener información de tensores

Cuando se trata de tensores, probablemente desee conocer los siguientes atributos:

- Shape
- Rank
- Axis or dimension 
- Size

In [ ]:
pd.DataFrame({'Atribute': ['Sape', 'Rank', 'Axis or dimension', 'Size'], 'Meaning': ['the length (number of elements) of each of the dimesions of a tensor','The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n','A particular dimension of a tensor', 'The total number of items in the tensor'], 'Code': ['tensor.shape', 'tensor.ndim', 'tensor[0], tensor[:, 1]', 'tf.size(tensor']})

Atribute                                            Meaning  \
0               Sape  the length (number of elements) of each of the...   
1               Rank  The number of tensor dimensions. A scalar has ...   
2  Axis or dimension                 A particular dimension of a tensor   
3               Size            The total number of items in the tensor   

                      Code  
0             tensor.shape  
1              tensor.ndim  
2  tensor[0], tensor[:, 1]  
3           tf.size(tensor

In [ ]:
# Crear un tensor con rank 4 (de 4 dimensiones)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
# Obtener varios atributos de un tensor
print(f'Datatype of every element: {rank_4_tensor.dtype}')
print(f'Número de dimensiones (rank): {rank_4_tensor.ndim}')
print(f'Forma o shape del tensor: {rank_4_tensor.shape}')
print(f'Elementos del eje (axis) 0: {rank_4_tensor.shape[0]}')
print(f'Elementos del último eje o axis: {rank_4_tensor.shape[-1]}')
print('Numero total de elementos en nuestro tensor: ', tf.size(rank_4_tensor))
print('Numero total de elementos en nuestro tensor: ', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Número de dimensiones (rank): 4
Forma o shape del tensor: (2, 3, 4, 5)
Elementos del eje (axis) 0: 2
Elementos del último eje o axis: 5
Numero total de elementos en nuestro tensor:  tf.Tensor(120, shape=(), dtype=int32)
Numero total de elementos en nuestro tensor:  120


### Indexar tensores

Los tensores se pueden indexar como una lista de python

In [ ]:
# Obtener los primeros 2 elementos para cada dimensión
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Obtener el primer elemento para cada dimensión por cada índice excepto para el final
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Crear un tensor de rank 2 (2 dimensiones)
rank_2_tensor = tf.constant([[10, 7], [3, 4], [2,6]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([3, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  6]], dtype=int32)>

In [ ]:
# Obtener el último artículo de cada fila de nuestro tensor
rank_2_tensor[:-1, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 3]], dtype=int32)>

In [ ]:
# Añadir una dimensión extra a unestro tensor de 2 dimensiones
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Los tres puntos lo que significa es en cada en cada entrada anterior lo aplique también se puede ver de la siguiente manera:
print('Agregar una entrada con los tres puntos' ,rank_3_tensor)
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
print('Agregar una entrada de forma manual' ,rank_3_tensor)
rank_3_tensor

Agregar una entrada con los tres puntos tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]

 [[ 2]
  [ 6]]], shape=(3, 2, 1), dtype=int32)
Agregar una entrada de forma manual tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]

 [[ 2]
  [ 6]]], shape=(3, 2, 1), dtype=int32)


<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]],

       [[ 2],
        [ 6]]], dtype=int32)>

In [ ]:
# Otra forma para agregar otra dimensión a nuestro tensor es tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # '-1' lo que significa es que lo vamos a expandir en el último eje

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]],

       [[ 2],
        [ 6]]], dtype=int32)>

In [ ]:
# Expandir el axis 0
tf.expand_dims(rank_2_tensor, axis=0) # '0' lo que significa es que lo vamos a expandir en el primer eje

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4],
        [ 2,  6]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  6]], dtype=int32)>

### Manipular Tensores(operaciones con tensores)
**Operaciones básicas**

`+`, `-`, `*`, `/`

In [ ]:
# Podemos sumar valores a un tensor usando el operador de `suma`
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# De esta manera no estamos afectando al tensor original
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Tambíen podemos multiplicar de la siguiente manera
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Si queremos también se puede restar
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# También podemos usar las funciones que vienen dentro de tensorflow
# Build-in Functions

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Nota**: para que las operaciones procesadas por `GPU` sean más rápidas es recomendable usar las `build-in-functions`

In [ ]:
 tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix Multiplication ó Multiplicación de Matrices **

En `Machine Learning` la multiplicación de matriceses es una de las operaciones más comunes.

## Encontrar la posicioón máxima y mínima

In [ ]:
# Crear un nuevo tensor para encontrar la posición mínima y máxima
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Encontrar la posición máxima
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Encontrar con nuestro index el valor mas grande
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Encontrar el valor mas grande de F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Comprobar la igualdad
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Encontrar la posición mínima
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Encontrar el mínimo usando el index mínimo
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### `Squeezing` o compactar un tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One Hot Encoding Tensors

In [ ]:
# Crear una lista de indices
some_list = [i for i in range(4)] # Puede ser Rojo, Verde, Azul, Purpura

# One Hot Codifica la lista de indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Especifique valores personalizados para una codificación activa
tf.one_hot(some_list, depth=4, on_value="el deep learning es muy bonito", off_value="Tambien me gusta correr carros")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'el deep learning es muy bonito',
        b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros'],
       [b'Tambien me gusta correr carros',
        b'el deep learning es muy bonito',
        b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros'],
       [b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros',
        b'el deep learning es muy bonito',
        b'Tambien me gusta correr carros'],
       [b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros',
        b'Tambien me gusta correr carros',
        b'el deep learning es muy bonito']], dtype=object)>

### Squaring, Log, Square Root

In [ ]:
# Crear un nuevo tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Encontrar la raiz cuadrada o squareroot
# De esta forma nos mandará un error ya que el método requiere un valor de punto flotante
try: 
    tf.sqrt(H)
except Exception as exce:
    print(exce)

Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]


Como podemos ver en la excepción la función requiere un valor de punto flotante para poder hacer la opercaión, por lo tanto debemos de cambiar el tipo de dato

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### tf.math.log

Calcula el algoritmo natural de x elemento

In [ ]:
# Encontrar el logaritmo natural o log
# Como podemos ver para este método de igual manera necesitamos un numero de punto flotante
try:
    tf.math.log(H)
except Exception as exce:
    print(exce)

Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log]


In [ ]:
# Modificamos el tipo de dato para poder ejecutarlo
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Crear un tensor directamente de un array de numpy
J = tf.constant(np.array([3,7,19], dtype=np.float32))
J

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 19.], dtype=float32)>

### Tensores y Numpy

TensorFlow interactúa muy bien con los arrays de numpy

🔑 **Note:** Una de las grandes diferencias entre los tensores de `Tensorflow` y los arrays de Numpy

In [ ]:
# Convertir nuestro tensor devuelta a un array de numpy
np.array(J), type(np.array(J))

(array([ 3.,  7., 19.], dtype=float32), numpy.ndarray)

In [ ]:
# Convertir el tensor J a un array de numpy
J.numpy(), type(J.numpy())

(array([ 3.,  7., 19.], dtype=float32), numpy.ndarray)

In [ ]:
J = tf.constant([3], dtype=tf.float32)
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

De esta forma podemos acceder al elemento

In [ ]:
J.numpy()[0]

3.0

In [ ]:
# los tipos predeterminados de cada uno son ligeramente diferentes
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Checar el tipo de dato de cada uno
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Encontrar acceso a las GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=2869a320-b9f1-4921-b902-9f4d298235ae' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>